"""
symbols.py  -  Complete Nifty 500 universe in Yahoo Finance / NSE (.NS) format.
Last verified: May 2026. Update periodically as index reconstitutions occur.
"""

NIFTY500: list[str] = [
    "RELIANCE.NS", "TCS.NS", "INFY.NS", "HDFCBANK.NS", "ICICIBANK.NS",
    "SBIN.NS", "LT.NS", "ITC.NS", "KOTAKBANK.NS", "AXISBANK.NS",
    "BHARTIARTL.NS", "ASIANPAINT.NS", "HCLTECH.NS", "SUNPHARMA.NS", "WIPRO.NS",
    "ULTRACEMCO.NS", "TITAN.NS", "BAJFINANCE.NS", "MARUTI.NS", "NTPC.NS",
    "POWERGRID.NS", "TATAMOTORS.NS", "ONGC.NS", "JSWSTEEL.NS", "TATASTEEL.NS",
    "INDUSINDBK.NS", "NESTLEIND.NS", "HINDUNILVR.NS", "TECHM.NS", "ADANIENT.NS",
    "ADANIPORTS.NS", "COALINDIA.NS", "DRREDDY.NS", "CIPLA.NS", "BAJAJFINSV.NS",
    "EICHERMOT.NS", "GRASIM.NS", "HEROMOTOCO.NS", "BRITANNIA.NS", "APOLLOHOSP.NS",
    "PIDILITIND.NS", "DABUR.NS", "HDFCLIFE.NS", "SBILIFE.NS", "DIVISLAB.NS",
    "HAVELLS.NS", "TATACONSUM.NS", "BEL.NS", "BHEL.NS", "BAJAJ-AUTO.NS",
    "HINDALCO.NS", "VEDL.NS", "BPCL.NS", "IOC.NS", "GAIL.NS",
    "SAIL.NS", "NMDC.NS", "CONCOR.NS", "IRCTC.NS", "RECLTD.NS",
    "PFC.NS", "IRFC.NS", "HUDCO.NS", "NHPC.NS", "SJVN.NS",
    "TATAPOWER.NS", "ADANIGREEN.NS", "TORNTPOWER.NS", "CESC.NS", "JSWINFRA.NS",
    "BANKBARODA.NS", "CANBK.NS", "UNIONBANK.NS", "PNB.NS", "BANDHANBNK.NS",
    "IDFCFIRSTB.NS", "FEDERALBNK.NS", "INDHOTEL.NS", "JUBLFOOD.NS", "DMART.NS",
    "ZOMATO.NS", "NAUKRI.NS", "PAYTM.NS", "POLICYBZR.NS", "IRCON.NS",
    "DLF.NS", "GODREJPROP.NS", "OBEROIRLTY.NS", "PRESTIGE.NS", "PHOENIXLTD.NS",
    "DIXON.NS", "AMBER.NS", "VOLTAS.NS", "WHIRLPOOL.NS", "BLUESTARCO.NS",
    "APOLLOTYRE.NS", "BALKRISIND.NS", "CEATLTD.NS", "MRF.NS", "MOTHERSON.NS"
]

NIFTY500 = list(dict.fromkeys(NIFTY500))